### ISSUE TITLE
Issue loading customised tasks

### ISSUE THREAD

**Issue by mandyWW** [buggyrace/buggy-race-server#203]
I can't seem to add new headings, for example I wanted to add a "Pre-requisite" heading but I got this error:

> Error parsing/adding tasks: bad section name "Pre" found in task source file at line 5

Not too much of an issue (I removed the heading in the end) but could be useful to document the requirement to stick to existing headings.

**Comment by davewhiteland** [comment]
Yes those sections are currently very fixed, because you're not uploading a document that's simply being rendered:  the markdown is being parsed back into the structure that is slotted into the database.  This is weakly documented in the [upload a custom markdown file](https://www.buggyrace.net/docs/customising/creating-tasks.html#or-upload-a-customised-markdown-file) section.

If we're going to add more sections, the database needs a new column — this is different from a problem loading the tasks, so I've made that a new issue: #205 and propose closing this one, as it's actually correct behaviour pending a change in what a task is.

**Comment by davewhiteland** [comment]
Closing this as I think it's represented by #205
