### ISSUE TITLE
No easy way to navigate back to the race server from tech notes

### ISSUE THREAD

**Issue by mandyWW** [buggyrace/buggy-race-server#222]
There is no header for navigation at the top of the tech notes page.

**Comment by mandyWW** [comment]
Actually sorry I just noticed navigation  under the image. I think I was confused as this is not consistent with how the Task pages for example look.

**Comment by davewhiteland** [comment]
Np, you are correct and there's a historical reason for this — tech notes did not used to be on the race server (they were an entirely separate GitHub-pages hosted site), which is why the navigation is missing...

...and that is still part of the problem, because they are generated as an entirely separate, static, standalone page. For this reason, announcements don't get displayed on tech notes either: they are 100% static HTML (unlike, for example, the task list... which looks different from the other race server pages but is in fact only partially static (because the markdown for all the task texts has been rendered into HTML in advance). Nothing is simple :-) )

It has it's own little navigation bar, but I think the "Race server" and "Tech notes" links should be the other way round, and maybe that link to the Race server could be a bit more prominent.

![Screenshot 2024-05-04 at 14 37 59](https://github.com/buggyrace/buggy-race-server/assets/111320/45a77f80-6f95-4eba-8bb2-0da4f2934665)

**Comment by davewhiteland** [comment]
I don't propose to ever bring the tech notes into the same race server navigation because there is always an option to host them entirely separately — that is, this year we've displaying customised tech notes on the (heroku-hosted) instance by editing the tech notes _inside_ the (forked) race server repo... but another way of doing this is to break the tech notes out as a completely separate set of files, and host them on GitHub pages, and point to them by setting `TECH_NOTES_EXTERNAL_URL` to point to that site.

It's going to be tricky to have the tech notes headers _optionally_ include the "live" header/nav from the race server without making that breaking-out-into-GitHub-Pages too complex.

**Comment by davewhiteland** [comment]
Closed by f16f40a with these rather feeble "fix":

![Screenshot 2024-05-07 at 09 45 50](https://github.com/buggyrace/buggy-race-server/assets/111320/ac70ad93-518b-4fee-b791-78ab51c6dd1d)

**Comment by davewhiteland** [comment]
actually... should make that nav bar "sticky" so it never scrolls off the top of the window frame as it's only one line high.

**Comment by davewhiteland** [comment]
Implemented in b524d2eccef2a2312774973dd8c80c2e2fc0f8ac
