### ISSUE TITLE
Add support for viewing which students have completed a specific task on the Admin dashboard

### ISSUE THREAD

**Issue by mandyWW** [buggyrace/buggy-race-server#239]
It would be very useful to be able to click on the numbers underneath `Total students' task texts` and see the names of the students who have completed each task.

**Comment by davewhiteland** [comment]
As we're finding how useful the texts information is, I think this might be well served richer information beyond the matrix (which is great for progress) — specifically, we do have broadly meaningful `created_at` and `modified_at` timestamps on the texts too which might be useful. So I think rather than adding a list of names to the dashboard, I might implement it as a whole page that you can click through which could show richer data than just _who_ but also _when_.

With a more advanced cohort of students, at some point this ought to be linked into their repos and version control — because the texts ought to be appearing in the Issues text (and perhaps commit messages)... but that's beyond the scope of this little project (something for GitHub classroom instead).

**Comment by davewhiteland** [comment]
Whilst implementing this I realised it's also probably very useful to see the list of students who _haven't_ authored a text for a specific task, so include that as a toggle

**Comment by davewhiteland** [comment]
closed: currently implement via the **Task text authors** button → `/admin/task-texts`.

It's not great. but it provides a way of seeing who's done what in a different grouping than the alphabetic-order of the text matrix

![Screenshot 2024-06-20 at 18 28 05](https://github.com/buggyrace/buggy-race-server/assets/111320/6f035c73-b206-45ca-9035-73f01c3bde13)
